### PR TITLE
Fix crash in get_properties function

### PR DESCRIPTION
**Pull request by dnaka91**
Fixing a crash due to a null pointer dereference in the various `get_properties` functions, which can happen if another plugin tries to get the possible properties with obs_get_source_properties through the libobs API.

In addition, move several integer constants to enums and adjust the outdated version number.

### CODE REVIEW

**Comment by FiniteSingularity** [comment]
Thank you very much for the PR.  I will review it today.

**Comment by FiniteSingularity** [comment]
This all looks great!  I'm not sure what happened with the version number, as I could have sworn I updated to 1.0.1 everywhere, but apparently not!  Good catch! Also, I like the use of enums- thats how I should have done things in the first place, and I should probably switch the integer defines over for the blur plugin as well.

**Comment by dnaka91** [comment]
Thanks for the kind words. I was worried that my change to enums might not be welcome :sweat_smile:. Thanks for your OBS plugins, they all work nice and I really enjoy them (the most meaningful plugins for me so far).

**Comment by FiniteSingularity** [comment]
No problem! I'm glad you're enjoying the plug-in.  And using an enum is IMO the right way to do it in this case.

**Pull request merged**
